#!/bin/bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${ROOT_DIR}"

OUTPUT_DIR="${OUTPUT_DIR:-/Users/magneto/Desktop/Codex Playground/Twist/generated/nist_cat_tests}"
BYTES_PER_CANDIDATE="${BYTES_PER_CANDIDATE:-1000000}"
COUNT="${COUNT:-64}"
SEED_BASE="${SEED_BASE:-11400714819323198485}"
PASSWORD_TEXT="${PASSWORD_TEXT:-cat}"

mkdir -p "${OUTPUT_DIR}"

echo "output_dir=${OUTPUT_DIR}"
echo "bytes_per_candidate=${BYTES_PER_CANDIDATE}"
echo "count=${COUNT}"
echo "password_text=${PASSWORD_TEXT}"

bash ./run_build_twist_battery_stream.sh >/dev/null

for ((i = 0; i < COUNT; ++i)); do
  seed=$((SEED_BASE + i))
  output_path="${OUTPUT_DIR}/candidate_$(printf '%02d' "${i}").bin"
  echo "[${i}/${COUNT}] ${output_path}"
  BYTES="${BYTES_PER_CANDIDATE}" \
  CANDIDATE_INDEX="${i}" \
  SEED="${seed}" \
  PASSWORD_TEXT="${PASSWORD_TEXT}" \
  OUTPUT_PATH="${output_path}" \
  bash ./run_emit_top_candidate_stream.sh >/dev/null
done

echo
echo "Generated byte streams:"
echo "  ${OUTPUT_DIR}"
